# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: blockchain.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'blockchain.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x62lockchain.proto\"\x86\x01\n\x05\x42lock\x12\x0c\n\x04size\x18\x01 \x01(\r\x12\x0c\n\x04hash\x18\x02 \x01(\x0c\x12\x0e\n\x06height\x18\x03 \x01(\r\x12\x1c\n\x06header\x18\x04 \x01(\x0b\x32\x0c.BlockHeader\x12\x19\n\x11transaction_count\x18\x05 \x01(\r\x12\x18\n\x02tx\x18\x06 \x03(\x0b\x32\x0c.Transaction\"\x80\x01\n\x0b\x42lockHeader\x12\x0f\n\x07version\x18\x01 \x01(\r\x12\x15\n\rprevious_hash\x18\x02 \x01(\x0c\x12\x13\n\x0bmerkle_root\x18\x03 \x01(\x0c\x12\x11\n\ttimestamp\x18\x04 \x01(\r\x12\x12\n\ndifficulty\x18\x05 \x01(\r\x12\r\n\x05nonce\x18\x06 \x01(\r\"\x8c\x01\n\x0bTransaction\x12\x0f\n\x07version\x18\x01 \x01(\x0c\x12\x14\n\x0cinputs_count\x18\x02 \x01(\r\x12\x15\n\x06inputs\x18\x03 \x03(\x0b\x32\x05.Utxo\x12\x15\n\routputs_count\x18\x04 \x01(\r\x12\x16\n\x07outputs\x18\x05 \x03(\x0b\x32\x05.Utxo\x12\x10\n\x08locktime\x18\x06 \x01(\r\"d\n\x04Utxo\x12\x0c\n\x04txid\x18\x01 \x01(\x0c\x12\r\n\x05index\x18\x02 \x01(\r\x12\x0e\n\x06sender\x18\x03 \x01(\x0c\x12\x10\n\x08receiver\x18\x04 \x01(\x0c\x12\x0e\n\x06\x61mount\x18\x05 \x01(\x04\x12\r\n\x05spent\x18\x06 \x01(\x08\"n\n\x07\x44\x62\x42lock\x12\x0c\n\x04hash\x18\x01 \x01(\x0c\x12\x0e\n\x06height\x18\x02 \x01(\r\x12\x1c\n\x06header\x18\x03 \x01(\x0b\x32\x0c.BlockHeader\x12\x19\n\x11transaction_count\x18\x04 \x01(\r\x12\x0c\n\x04txid\x18\x05 \x03(\x0c\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'blockchain_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BLOCK']._serialized_start=21
  _globals['_BLOCK']._serialized_end=155
  _globals['_BLOCKHEADER']._serialized_start=158
  _globals['_BLOCKHEADER']._serialized_end=286
  _globals['_TRANSACTION']._serialized_start=289
  _globals['_TRANSACTION']._serialized_end=429
  _globals['_UTXO']._serialized_start=431
  _globals['_UTXO']._serialized_end=531
  _globals['_DBBLOCK']._serialized_start=533
  _globals['_DBBLOCK']._serialized_end=643
# @@protoc_insertion_point(module_scope)
