# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protobuf.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'protobuf.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eprotobuf.proto\"j\n\x05Input\x12\x0c\n\x04txid\x18\x01 \x01(\t\x12\x12\n\nutxo_index\x18\x02 \x01(\r\x12\x0e\n\x06sender\x18\x03 \x01(\t\x12\x10\n\x08receiver\x18\x04 \x01(\t\x12\x0e\n\x06\x61mount\x18\x05 \x01(\t\x12\r\n\x05spent\x18\x06 \x01(\x08\"k\n\x06Output\x12\x0c\n\x04txid\x18\x01 \x01(\t\x12\x12\n\nutxo_index\x18\x02 \x01(\r\x12\x0e\n\x06sender\x18\x03 \x01(\t\x12\x10\n\x08receiver\x18\x04 \x01(\t\x12\x0e\n\x06\x61mount\x18\x05 \x01(\t\x12\r\n\x05spent\x18\x06 \x01(\x08\"<\n\x06TxBody\x12\x0f\n\x07msg_str\x18\x01 \x01(\t\x12\x0e\n\x06pubkey\x18\x02 \x01(\t\x12\x11\n\tsignature\x18\x03 \x01(\t\"\x84\x01\n\x0bTransaction\x12\x0c\n\x04txid\x18\x01 \x01(\t\x12\x16\n\x06inputs\x18\x02 \x03(\x0b\x32\x06.Input\x12\x18\n\x07outputs\x18\x03 \x03(\x0b\x32\x07.Output\x12\x15\n\x04\x62ody\x18\x04 \x01(\x0b\x32\x07.TxBody\x12\x11\n\ttimestamp\x18\x05 \x01(\x04\x12\x0b\n\x03raw\x18\x63 \x01(\t\"\xe8\x01\n\x05\x42lock\x12\x0e\n\x06height\x18\x01 \x01(\r\x12\x0f\n\x07version\x18\x02 \x01(\r\x12\x15\n\rprevious_hash\x18\x03 \x01(\t\x12\x12\n\nblock_hash\x18\x04 \x01(\t\x12\x13\n\x0bmerkle_root\x18\x05 \x01(\t\x12\x11\n\ttimestamp\x18\x06 \x01(\x04\x12\x0c\n\x04\x62its\x18\x07 \x01(\r\x12\r\n\x05nonce\x18\x08 \x01(\r\x12\x15\n\rminer_address\x18\t \x01(\t\x12\x0e\n\x06tx_ids\x18\n \x03(\t\x12\'\n\x11\x66ull_transactions\x18\x0b \x03(\x0b\x32\x0c.Transactionb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protobuf_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INPUT']._serialized_start=18
  _globals['_INPUT']._serialized_end=124
  _globals['_OUTPUT']._serialized_start=126
  _globals['_OUTPUT']._serialized_end=233
  _globals['_TXBODY']._serialized_start=235
  _globals['_TXBODY']._serialized_end=295
  _globals['_TRANSACTION']._serialized_start=298
  _globals['_TRANSACTION']._serialized_end=430
  _globals['_BLOCK']._serialized_start=433
  _globals['_BLOCK']._serialized_end=665
# @@protoc_insertion_point(module_scope)
